### ISSUE TITLE
Postcss not doing anything

### ISSUE THREAD

**Issue by kr8n3r** [jedmao/postcss-middleware#11]
the current setup
```js
app.use(sassMiddleware({
  /* Options */
  src: paths.globalScss,
  dest: path.join(__dirname, 'public/css'),
  debug: true,
  outputStyle: 'expanded',
  prefix: '/public/css'
}))

app.use('/public/css', postcssMiddleware({
  plugins: [autoprefixer()],
  src: function (req) {
    return path.join(__dirname, 'public', 'css', req.path)
  }
}))

app.use('/public', express.static(path.join(__dirname, 'public')))
```
sass middleware creates the file, but postcss doesnt add vendor prefixes.

anyone has any ideas?

**Comment by bellizio** [comment]
I am experiencing the same issue @igloosi has described and my config is essentially the same, just with different paths.

**Comment by johnnyluu** [comment]
Same issue here :(

**Comment by johnnyluu** [comment]
Turns out, the plugin doesn't update the file on the file system, it sends the processed css file directly to the browser. So it works, just doesn't update the local copy of the file.

**Comment by jednano** [comment]
Isn't that what it's supposed to do?

**Comment by naoyeye** [comment]
@johnnyluu u r right! bro! thanks!

so, it works!


my  scss code:
![image](https://user-images.githubusercontent.com/434428/37640555-2af1804c-2c51-11e8-83b3-4875efebd111.png)

scss => css
![image](https://user-images.githubusercontent.com/434428/37640571-3e9c0fae-2c51-11e8-843a-4f503576a092.png)

css in browser:

![image](https://user-images.githubusercontent.com/434428/37640501-e14450b4-2c50-11e8-90ab-4b92c4057cba.png)

**Comment by jednano** [comment]
Looks like a non-issue then. Closing.
