### ISSUE TITLE
Not processing css files

### ISSUE THREAD

**Issue by sahat** [jedmao/postcss-middleware#4]
Not sure what I am doing wrong here, but the postcss-middleware seems to completely ignore all postcss plugins.

Using Express application:

``` js
var postcss = require('postcss-middleware');
var cssnext = require('postcss-cssnext');
var postcssImport = require('postcss-import');
var autoprefixer = require('autoprefixer');

app.use('/css', postcss({
  src: function(req) {
    return path.join(__dirname, 'public', req.path);
  },
  plugins: [postcssImport, cssnext, autoprefixer]
}));
```

I have 3 CSS files in **public/css** (default Express boilerplate path). Two files are imported via `@import` into main.css.

Inspecting Network tab, no CSS properties are autoprefixed and two extra are filed are not inline-styled into main.css, so there is something wrong with the middleware config.

**Comment by jednano** [comment]
Have you tried the following?

``` js
plugins: [
  postcssImport(),
  cssnext(),
  autoprefixer()
]
```

**Comment by sahat** [comment]
That did not work for me. To give some more details here is a screenshot and a list of all my Express middlewares.

![sshot-11](https://cloud.githubusercontent.com/assets/544954/14993435/c96c1362-1138-11e6-99be-c5e0b3871476.png)

``` js
var app = express();

app.use('/css', postcss({
  src: function(req) {
    return path.join(__dirname, 'public', req.path);
  },
  plugins: [postcssImport(), cssnext(), autoprefixer()]
}));

mongoose.connect(process.env.MONGODB);

app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');
app.set('port', process.env.PORT || 3000);
app.use(compression());
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(expressValidator());
app.use(methodOverride('_method'));
app.use(session({ secret: 'keyboard cat', resave: true, saveUninitialized: true }));
app.use(flash());
app.use(passport.initialize());
app.use(passport.session());
app.use(express.static(path.join(__dirname, 'public')));
```

**Comment by jednano** [comment]
@sahat I have no idea what may be going wrong. I created this library for an immediate need, which has since been replaced by the webpack method. Have you tried webpack?

**Comment by sahat** [comment]
Ok I figured out the problem. It was totally me. For whatever reason I expected the `req.path` to be `/css/main.css` (that's what I have in my HTML) or perhaps because postcss-middleware's first argument is `/css` I had assumed it would be part of the `req.path`.

Anyway, a simple fix in path solved the issue.

```
path.join(__dirname, 'public', 'css', req.path);
```

Thanks.

**Comment by sahat** [comment]
@jedmao Yeah I use webpack in some of my projects. For this particular project, I am giving users a choice between webpack, gulp, npm scripts and connect middleware for postcss transformation. So I have to implement all 4 possible ways of working with PostCSS! :)

**Comment by jednano** [comment]
Sounds like an interesting project. Glad you could figure out the issue!
