### ISSUE TITLE
Skip non css files

### ISSUE THREAD

**Issue by marchenko1985** [jedmao/postcss-middleware#8]
Not sure if it is by design so no PR

Will be nice if there will be check like in [node-sass-middleware lines 121-123](https://github.com/sass/node-sass-middleware/blob/master/middleware.js#L121-L123) so your middleware will be applied only to css files

In my case I'm trying to figure out how to have both stylesheet and javascript related middlewares in one app for development

**Comment by jednano** [comment]
If you only want it applied to CSS files then just make sure your [`options.src`](https://github.com/jedmao/postcss-middleware#src) glob only includes CSS files. Thing is, for you, the extension may be `.css` but for others it might be `.sss` or something else, so it's up to you to tell me which files are CSS by indicating such in your `options.src` glob.
