### ISSUE TITLE
Having issues with typescript 2.1.5

### ISSUE THREAD

**Issue by ShaharHD** [jedmao/postcss-middleware#9]
My project is based on typescript 2.1.5 and while importing postcss-middleware (tested even as a seperate ts file) I'm getting many errors from tsc regarding duplicate identifiers and interface Server ,ServerResponse, etc.
with errors as:
```

file: '.../node_modules/%40types/node/index.d.ts'
severity: 'Error'
message: 'Interface 'ServerResponse' cannot simultaneously extend types 'Writable' and 'EventEmitter'.
  Named property 'emit' of types 'Writable' and 'EventEmitter' are not identical.'
at: '640,22'
source: 'ts'
```

my tsconfig file is:

```
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "noImplicitAny": false,
    "removeComments": true,
    "preserveConstEnums": true,
    "noUnusedLocals": true,
    "outDir": "build",
    "sourceMap": true,
    "watch": false,
    "pretty": true
  },
  "compileOnSave": true,
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts",
    "build/**/*"
  ]
}
```

**Comment by jednano** [comment]
Yeah this code hasn't been updated to the newest version of TS. Are you requiring a ts file from this project directly? You shouldn't need to compile files in this project w/ your setup, I think.

**Comment by ShaharHD** [comment]
Maybe I'm doing something wrong, but pretty straight forward from my ts file I'm calling the following:

```typescript
import * as autoprefixer from 'autoprefixer';
import * as postcssMiddleware from 'postcss-middleware';
```

```typescript
    this.app.use(postcssMiddleware({
      plugins: [
        // Plugins

        autoprefixer({
          browsers: [
            '>1%',
            'last 4 versions',
            'Firefox ESR',
            'not ie < 9', // React doesn't support IE8 anyway
          ],
        }),
      ],
      src: (req) => {
        return path.join(postcssDir, req.url);
      },
    }));
```

**Comment by jednano** [comment]
BTW, what makes you think the error you posted above has anything to do with this package? Perhaps you need to isolate the problem down to only the part that's failing. Try not using autoprefixer, for example. Eliminate anything else that might be a point of failure.

**Comment by ShaharHD** [comment]
I did. I left only postcssMiddleware in the import.

Even more, I actually created a separate ts file just to test this - as at first I thought it had something to do with the other middlewares.

**Comment by ShaharHD** [comment]
I can create a sample project to show the issue.

**Comment by jednano** [comment]
How did you install `postcss-middleware` and can you dive into your `node_modules` folder and tell me the extension name of the files that are installed? Are there `ts` files in there or `js` files?

**Comment by jednano** [comment]
Also, are you using webpack by chance?

**Comment by ShaharHD** [comment]
no webpack.
it's a Typescript 2.x ExpressJS scaffolding I did on my own to cleanup stuff.

Then a friend asked me to add postcss to it (for his use) - and that's when I got this error.

I've installed postcss-middleware using yarn (```yarn add postcss-middleware```). nothing out of the ordinary.

The actual folder in node_modules list the files as:

```
CHANGELOG.md	LICENSE		README.md	dist		fixtures	gulpfile.ts	package.json	typings
```

and dist/lib/
```
middleware.d.ts	middleware.js
```

**Comment by jednano** [comment]
Thanks, that's very helpful. I think the d.ts file has to be recompiled with TypeScript latest to resolve this issue. Let me see how trivial that is.

**Comment by jednano** [comment]
@ShaharHD let me know if version 1.1.3 doesn't solve your issue.

**Comment by ShaharHD** [comment]
No errors now 👍 

Thank you!
I'll post here if after testing there are additional issues.
